/* Copyright (C) Harry Clark 2023 */

/* Michael Jackson Moonwalker Disassembly */

/* THIS FILE PERTAINS TO ALL OF THE EXTERN FUNCTIONS AMIDST THE RAW DISASSMBLY */
/* THIS IS HERE FOR RESEARCH PURPOSES AS I AM UNSURE OF WHICH FUNCTIONS CORRESPOND */
/* TO WHICH ARGUMENTS AS OF JULY 10TH 2023 */

#ifndef EXTERNS
#define EXTERNS

extern void FUN_000005d2(void);
extern void FUN_00015020(void); // THIS ONE HAS SOMETHING TO DO WITH THE Z80 BUS BEING NULL, 
                                // POSSIBLY A Z80 FREE METHOD

#endif